services:
  cowrie:
    image: cowrie/cowrie:latest
    container_name: hp_cowrie
    ports:
      - '2222:2222'
      - '2223:2223'
    volumes:
      - ./logs/cowrie:/cowrie/var/log/cowrie
      - ./cowrie/cowrie.cfg:/cowrie/cowrie.cfg:ro
    environment:
      - COWRIE_LOG_LEVEL=INFO
    restart: unless-stopped
    networks:
      - hp_net

  dionaea:
    image: dinotools/dionaea:latest
    container_name: hp_dionaea
    restart: unless-stopped
    ports:
      - '21:21'
      - '8081:80'
      - '3306:3306'
      - '69:69/udp'
    volumes:
      - ./data/dionaea:/opt/dionaea/var/lib/dionaea
      - ./logs/dionaea:/opt/dionaea/var/log/dionaea
      - ./config/dionaea:/opt/dionaea/etc/dionaea:ro
    networks:
      - hp_net
    cap_add:
      - NET_ADMIN

  pyrdp:
    image: gosecure/pyrdp:latest
    container_name: hp_pyrdp
    # Оставляем tee, но Vector будет читать чистый лог из папки logs
    command: sh -c "pyrdp-mitm --transparent -o /output 2>&1 | tee /var/log/pyrdp/pyrdp.log"
    volumes:
      - ./pyrdp_output:/output
      - ./logs/pyrdp:/var/log/pyrdp
    ports:
      - "3389:3389"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - hp_net

  postgresql-honeypot:
    build: ./postgresql-honeypot
    container_name: hp_postgres_0xnslabs
    ports:
      - "5432:5432"
    volumes:
      - ./logs/postgresql-honeypot:/app/logs
    restart: unless-stopped
    networks:
      - hp_net

  vector:
    image: timberio/vector:0.48.0-debian
    container_name: hp_vector
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./vector.yaml:/etc/vector/vector.yaml:ro
      - ./logs:/var/log/honeypots:ro
    ports:
      - "8686:8686"
    command: ["--config", "/etc/vector/vector.yaml"]
    networks:
      - hp_net
    depends_on:
      - loki
      - postgresql-honeypot

  loki:
    image: grafana/loki:latest
    container_name: hp_loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    networks:
      - hp_net

  grafana:
    image: grafana/grafana:latest
    container_name: hp_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - hp_net

networks:
  hp_net:
    driver: bridge
